Add logo files
pythonpune/design pull request #3
Opened 2019-11-11 16:17 UTC by akshay196

Include logo files in
  - Transparent background
  - White background
  - Black background
  - Single color logo
  - SVG file

2019-11-12 16:39 UTC, digitronik approved these changes
Awesome LGTM
![580b57fcd9996e24bc43c4c4](https://user-images.githubusercontent.com/11618054/67802434-234e4c00-fab1-11e9-9dde-38e46cf5b4b5.png)

2019-11-13 13:30 UTC, bhavin192 requested changes
Can you please add LICENSE to this repository (same license can also apply to the logo as well, it's upto you to choose the license for the logo). Also we need to add a copyright line about the logo in README.md something like this:
```
Copyright © 2019 PythonPune
or
Copyright © 2019 Akshay Gaikwad
```
Again it's upto you who holds the copyright of the logo :)

2019-11-13 17:34 UTC, akshay196 commented
@bhavin192 @digitronik Thanks :smile:   Added LICENSE here.

2019-11-13 17:57 UTC, bhavin192 approved these changes

2019-11-14 04:04 UTC, merged